# Generated by Django 5.2.6 on 2025-10-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
