# Generated by Django 5.2.6 on 2025-10-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0002_remove_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
