# Generated by Django 5.2.6 on 2025-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0003_orders_product_image_alter_orders_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ids',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
