# Generated by Django 5.2.6 on 2025-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0004_orders_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ids',
            field=models.CharField(max_length=10),
        ),
    ]
