# Generated by Django 5.2.6 on 2025-11-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0005_alter_orders_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
