# Generated by Django 5.2.6 on 2025-11-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0006_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=40)),
                ('product_image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
