# Generated by Django 5.2.6 on 2025-11-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
