# Generated by Django 5.2.6 on 2025-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_app', '0009_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('username', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postc', models.CharField(max_length=15)),
                ('payment_method', models.CharField(default='Razorpay', max_length=15)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
